import jsPDF from "jspdf";

// ── Shared helpers ───────────────────────────────────────────────────────────

const BRAND   = "Teamosis Accounts";
const PRIMARY = [15, 118, 110]  as [number, number, number]; // brand teal
const DARK    = [13,  17,  23]  as [number, number, number]; // ink-white (dark text)
const MUTED   = [94, 107, 130]  as [number, number, number]; // ink-secondary
const LINE    = [209, 217, 230] as [number, number, number]; // surface-border
const RED_C   = [239, 68,  68]  as [number, number, number];
const GREEN_C = [16,  185, 129] as [number, number, number];
const BLUE_C  = [59,  130, 246] as [number, number, number];

const PAGE_W = 210; // A4 mm
const ML = 16;      // left margin
const MR = PAGE_W - 16; // right edge
const COL_R = MR;  // right-align column x

function usd(n: number) {
  return n < 0
    ? `($${Math.abs(n).toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 })})`
    : `$${n.toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function bdt(n: number) {
  return `৳${Math.abs(n).toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function drawHeader(doc: jsPDF, title: string) {
  // Top colour bar
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, PAGE_W, 14, "F");

  // Company name in bar
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(BRAND, ML, 9.5);

  // Report title below bar
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DARK);
  doc.text(title, ML, 28);

  return 36; // y cursor after header
}

function drawMeta(doc: jsPDF, y: number, pairs: [string, string][]) {
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  let x = ML;
  for (const [label, value] of pairs) {
    doc.setTextColor(...MUTED);
    doc.text(label + ":", x, y);
    doc.setTextColor(...DARK);
    doc.text(value, x + doc.getTextWidth(label + ": "), y);
    x += 70;
  }
  return y + 8;
}

function hRule(doc: jsPDF, y: number, thick = false) {
  doc.setDrawColor(...(thick ? DARK : LINE));
  doc.setLineWidth(thick ? 0.5 : 0.3);
  doc.line(ML, y, MR, y);
  return y + 4;
}

function sectionTitle(doc: jsPDF, y: number, text: string) {
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...MUTED);
  doc.text(text.toUpperCase(), ML, y);
  return y + 5;
}

function lineItem(
  doc: jsPDF,
  y: number,
  label: string,
  amount: string,
  color: [number, number, number] = DARK,
  indent = 0,
  bold = false
) {
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(10);
  doc.setTextColor(...DARK);
  doc.text(label, ML + indent, y);
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setTextColor(...color);
  doc.text(amount, COL_R, y, { align: "right" });
  return y + 6.5;
}

function drawFooter(doc: jsPDF) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const pageH = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.3);
    doc.line(ML, pageH - 12, MR, pageH - 12);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(
      `Generated by ${BRAND} · ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`,
      ML, pageH - 7
    );
    doc.text(`Page ${i} of ${total}`, COL_R, pageH - 7, { align: "right" });
  }
}

// ── Income Statement ─────────────────────────────────────────────────────────

interface IncomeStatementData {
  entityName: string;
  from: string;
  to: string;
  income: { total: number; currency: string };
  expenses: { total: number; currency: string; byCategory: { category: string; amount: number }[] };
  grossProfit: number;
  netProfit: number;
}

export function exportIncomeStatementPDF(data: IncomeStatementData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  let y = drawHeader(doc, "Income Statement");
  y = drawMeta(doc, y, [
    ["Entity", data.entityName],
    ["Period", `${data.from} to ${data.to}`],
  ]);
  y = hRule(doc, y + 2);

  // Revenue
  y = sectionTitle(doc, y, "Revenue");
  y = lineItem(doc, y, "Total Income", usd(data.income.total), GREEN_C, 4);
  y = hRule(doc, y + 1);

  // Expenses
  y = sectionTitle(doc, y, "Operating Expenses");

  if (data.expenses.byCategory.length > 0) {
    for (const cat of data.expenses.byCategory) {
      // Check if we need a new page
      if (y > 260) { doc.addPage(); y = 20; }
      y = lineItem(doc, y, cat.category || "Other", `(${usd(cat.amount)})`, RED_C, 4);
    }
  } else {
    y = lineItem(doc, y, "No expenses recorded", usd(0), MUTED, 4);
  }

  y = hRule(doc, y + 1);
  y = lineItem(doc, y, "Total Expenses", `(${usd(data.expenses.total)})`, RED_C, 0, true);
  y += 2;

  // Profit
  y = hRule(doc, y, true);
  y = lineItem(doc, y, "Gross Profit", usd(data.grossProfit), data.grossProfit >= 0 ? GREEN_C : RED_C, 0, true);
  y += 1;
  y = lineItem(doc, y, "Net Profit", usd(data.netProfit), data.netProfit >= 0 ? BLUE_C : RED_C, 0, true);

  // Net profit box highlight
  doc.setFillColor(...(data.netProfit >= 0 ? GREEN_C : RED_C));
  doc.setOpacity(0.08);
  doc.rect(ML - 2, y - 10, MR - ML + 4, 8, "F");
  doc.setOpacity(1);

  drawFooter(doc);
  doc.save(`income-statement_${data.entityName.replace(/\s+/g, "-")}_${data.from}_${data.to}.pdf`);
}

// ── Balance Sheet ────────────────────────────────────────────────────────────

interface BalanceSheetData {
  entityName: string;
  from: string | null;
  to: string;
  assets: { label: string; amount: number; currency: string }[];
  totalAssets: number;
  equity: number;
}

export function exportBalanceSheetPDF(data: BalanceSheetData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  let y = drawHeader(doc, "Balance Sheet");
  y = drawMeta(doc, y, [
    ["Entity", data.entityName],
    ["Period", data.from ? `${data.from} to ${data.to}` : `As of ${data.to}`],
  ]);
  y = hRule(doc, y + 2);

  // Assets
  y = sectionTitle(doc, y, "Assets");
  for (const asset of data.assets) {
    const amtStr = asset.currency === "BDT" ? bdt(asset.amount) : usd(asset.amount);
    y = lineItem(doc, y, asset.label, amtStr, BLUE_C, 4);
  }
  y = hRule(doc, y + 1);
  y = lineItem(doc, y, "Total Assets", usd(data.totalAssets), BLUE_C, 0, true);
  y += 6;

  // Equity
  y = hRule(doc, y, true);
  y += 2;
  y = sectionTitle(doc, y, "Equity");
  y = lineItem(doc, y, "Total Equity", usd(data.equity), data.equity >= 0 ? GREEN_C : RED_C, 4, true);

  // Equity note
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(...MUTED);
  doc.text("Equity = Cumulative Income − Cumulative Expenses for the selected period", ML + 4, y + 2);
  y += 10;

  // Equity highlight box
  doc.setFillColor(...(data.equity >= 0 ? GREEN_C : RED_C));
  doc.setOpacity(0.07);
  doc.rect(ML - 2, y - 22, MR - ML + 4, 14, "F");
  doc.setOpacity(1);

  // Balance check
  y += 4;
  y = hRule(doc, y);
  const balanced = Math.abs(data.totalAssets - data.equity) < 1;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...(balanced ? GREEN_C : RED_C));
  doc.text(
    balanced ? "✓ Balance sheet is balanced" : "⚠ Assets and equity do not balance — review transactions",
    ML, y + 4
  );

  drawFooter(doc);
  doc.save(`balance-sheet_${data.entityName.replace(/\s+/g, "-")}_${data.to}.pdf`);
}
